name: Check Reminders

on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Check reminders and notify
        uses: agrc/reminder-action@v1
